apps:
  api:
    repo_name: digitalmarketplace-api
    bootstrap: invoke requirements-dev run-migrations

  search-api:
    repo_name: digitalmarketplace-search-api
    bootstrap: invoke requirements-dev

  admin-frontend:
    repo_name: digitalmarketplace-admin-frontend
    bootstrap: invoke requirements-dev frontend-build

  brief-responses-frontend:
    repo_name: digitalmarketplace-brief-responses-frontend
    bootstrap: invoke requirements-dev frontend-build

  briefs-frontend:
    repo_name: digitalmarketplace-briefs-frontend
    bootstrap: invoke requirements-dev frontend-build

  buyer-frontend:
    repo_name: digitalmarketplace-buyer-frontend
    bootstrap: invoke requirements-dev frontend-build

  supplier-frontend:
    repo_name: digitalmarketplace-supplier-frontend
    bootstrap: invoke requirements-dev frontend-build

  user-frontend:
    repo_name: digitalmarketplace-user-frontend
    bootstrap: invoke requirements-dev frontend-build
